version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NGINX_HOST=frontend
      - NGINX_PORT=80
    
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=host.docker.internal
      - MYSQL_DATABASE=modelBillingDBv1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root
    volumes:
      - ./backend:/app
