version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SET_BASE_URL: ${SET_BASE_URL}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - SET_BASE_URL=${SET_BASE_URL}

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
