version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: modelBillingDBv1
      MYSQL_USER: server
      MYSQL_PASSWORD: Server
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  db_data:
